all:
	gcc -c 121044046_main.c
	gcc -o floristApp 121044046_main.o -lpthread -lm

debug:
	gcc -DDEBUG -c 121044046_main.c
	gcc -o floristApp 121044046_main.o -lpthread -lm

clean:
	rm -f floristApp 121044046_main.o
